# Generated by Django 5.0.3 on 2024-03-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
