# Generated by Django 5.0.3 on 2024-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_record_first_name_alter_record_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
