# Generated by Django 5.0.3 on 2024-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_record_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
